services:
  fastapi-app:
    build: .
    ports:
      - "8080:8000"
    environment:
      PINECONE_API_KEY: "PINECONE_API_KEY"
      PINECONE_ENVIRONMENT: "PINECONE_ENVIRONMENT"
      REDIS_HOST: "redis"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
