services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyskb-local
    ports:
      - "8080:8000"  # Map container port 8000 to localhost 8080
    env_file:
      - ./env/.env.local  # Use .env.local file to load environment variables
    environment:
      ENVIRONMENT: development  # Explicitly specify the environment
      PYTHONPATH: /app  # Ensure the correct Python path for the application
    volumes:
      - ./src:/app/src  # Updated to mount the "src" folder instead of "app"
      - ./logs:/app/logs  # Mount the logs directory for persistent logging (local only)
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Updated "app.main" to "src.main"
    depends_on:
      - redis  # Ensure Redis starts before the FastAPI app
    restart: always  # Automatically restart the app if it crashes

  redis:
    image: redis:7.0  # Specify the Redis version
    ports:
      - "6379:6379"  # Map container Redis port to localhost
    volumes:
      - ./redis-data:/data  # Mount Redis data directory for persistence
    restart: always  # Automatically restart Redis if it crashes
