services:
  fastapi-app:
    build: .
    ports:
      - "8080:8000"  # Map container port 8000 to localhost 8080
    volumes:
      - ./app:/app  # Mount local app directory for live code updates
      - ./logs:/app/logs  # Mount logs directory to persist logs
      - ./env/.env.local:/app/.env.local  # Mount .env.local into the container
    environment:
      PINECONE_API_KEY: "${PINECONE_API_KEY}"  # Pass Pinecone API key
      KNOWLEDGE_API_KEY: "${KNOWLEDGE_API_KEY}"  # Pass Knowledge API key
      OPENAI_API_KEY: "${OPENAI_API_KEY}"  # Pass OpenAI API key
      REDIS_HOST: "redis"  # Set Redis host
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis  # Ensure Redis starts before FastAPI app
    restart: always  # Automatically restart the app if it crashes

  redis:
    image: redis:7.0  # Specify the Redis version
    ports:
      - "6379:6379"  # Map container Redis port to localhost
    volumes:
      - ./redis-data:/data  # Mount Redis data directory for persistence
    restart: always  # Automatically restart Redis if it crashes
