services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyskb-local
    ports:
      - "8080:8000"  # Map container port 8000 to localhost 8080
    env_file:
      - ./env/.env.local  # Use env_file like in production
    environment:
      ENVIRONMENT: development
      PYTHONPATH: /app  # Ensure correct Python path
    volumes:
      - ./app:/app  # Mount local app directory for live code updates
      - ./logs:/app/logs  # Mount logs directory to persist logs (local only)
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis  # Ensure Redis starts before FastAPI app
    restart: always  # Automatically restart the app if it crashes

  redis:
    image: redis:7.0  # Specify the Redis version
    ports:
      - "6379:6379"  # Map container Redis port to localhost
    volumes:
      - ./redis-data:/data  # Mount Redis data directory for persistence
    restart: always  # Automatically restart Redis if it crashes
