services:
  fastapi-app:
    image: pyskbregistry.azurecr.io/py-skb:prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
        AZURE_KEY_VAULT_NAME: skb-keyvault
    ports:
      - "80:8000"  # Expose FastAPI app on HTTP port 80
    env_file:
      - ./env/.env.prod  # Use env_file for production
    environment:
      PYTHONPATH: /app  # Explicitly define PYTHONPATH
      REDIS_HOST: redis  # Explicit override if needed
    depends_on:
      - redis  # Ensure Redis starts before FastAPI app
    restart: always  # Automatically restart the app if it crashes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"  # Expose Redis on the default port
    volumes:
      - redis-data:/data  # Persistent Redis storage
    restart: always  # Automatically restart on failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
